fragment CartFields on Cart {
  __typename
  id
  totalQuantity
  checkoutUrl
  cost {
    subtotalAmount {
      __typename
      amount
      currencyCode
    }
    totalAmount {
      __typename
      amount
      currencyCode
    }
    totalTaxAmount {
      __typename
      amount
      currencyCode
    }
  }
  lines(first: 250) {
    __typename
    edges {
      __typename
      node {
        ... on CartLine {
          __typename
          ...LineItemFields
        }
      }
    }
  }
}

query GetCart($cartId: ID!) {
  cart(id: $cartId) {
    ...CartFields
  }
}

mutation RemoveCartItem($cartId: ID!, $lineItemId: ID!) {
  cartLinesRemove(cartId: $cartId, lineIds: [$lineItemId]) {
    cart {
      ...CartFields
    }
  }
}

mutation UpdateCartItem($cartId: ID!, $lineItemId: ID!, $quantity: Int!) {
  cartLinesUpdate(
    cartId: $cartId
    lines: [{ id: $lineItemId, quantity: $quantity }]
  ) {
    cart {
      ...CartFields
    }
  }
}

mutation AddCartItem($cartId: ID!, $lineItem: CartLineInput!) {
  cartLinesAdd(cartId: $cartId, lines: [$lineItem]) {
    cart {
      ...CartFields
    }
  }
}

mutation CreateCart($input: CartInput) {
  cartCreate(input: $input) {
    cart {
      ...CartFields
    }
    userErrors {
      code
      message
    }
  }
}

mutation CartAttributesUpdate(
  $cartId: ID!
  $buyerIdentidy: CartBuyerIdentityInput!
  $attributes: [AttributeInput!]!
) {
  cartAttributesUpdate(attributes: $attributes, cartId: $cartId) {
    __typename
  }
  cartBuyerIdentityUpdate(cartId: $cartId, buyerIdentity: $buyerIdentidy) {
    __typename
    cart {
      checkoutUrl
    }
  }
}
