fragment ProductFields on Product {
  id
  handle
  title
  description
  availableForSale
  totalInventory
  vendor
  productType
  featuredImage {
    __typename
    id
    url(transform: { maxHeight: 250, maxWidth: 250, scale: 2 })
    altText
    width
    height
  }
  thruga: metafield(namespace: "custom", key: "thruga") {
    value
    type
  }
  country: metafield(namespace: "custom", key: "country") {
    value
    type
  }
  region: metafield(namespace: "custom", key: "region") {
    value
    type
  }
  wineType: metafield(namespace: "custom", key: "wine_type") {
    value
    type
  }
  framleidandi: metafield(namespace: "custom", key: "framleidandi") {
    value
    type
  }
  raektun: metafield(namespace: "custom", key: "raektun") {
    value
    type
  }
  abv: metafield(namespace: "custom", key: "abv") {
    value
    type
  }
  magn: metafield(namespace: "custom", key: "magn") {
    value
    type
  }
  variants(first: 10) {
    edges {
      node {
        ...VariantFields
      }
    }
  }
}
