query Products($after: String, $filters: [ProductFilter!]) {
  collection(handle: "in-stock") {
    products(first: 100, after: $after, filters: $filters) {
      ...PaginatedProductList
    }
  }
}

query ProductsByIds($ids: [ID!]!) {
  nodes(ids: $ids) {
    ... on Product {
      __typename
      ...ProductFields
    }
  }
}
