fragment VariantFields on ProductVariant {
  __typename
  id
  title
  availableForSale
  quantityAvailable
  image {
    __typename
    id
    url(transform: { maxHeight: 1200, maxWidth: 1200, scale: 2 })
    altText
    width
    height
  }
  price {
    __typename
    amount
    currencyCode
  }
  compareAtPrice {
    __typename
    amount
    currencyCode
  }
}
