query HomePage {
  homePage {
    id
    newProducts {
      id
      shopifyProductId
    }
    _seoMetaTags {
      attributes
      content
      tag
    }
    seo {
      title
      description
      image {
        responsiveImage(imgixParams: { w: 1200, h: 630 }) {
          width
          height
          src
          alt
        }
      }
    }
    post {
      id
      slug
      title
      date
      excerpt
      content {
        __typename
        blocks {
          __typename
          id
          ... on ProductRecord {
            shopifyProductId
          }
        }
      }
      image {
        responsiveImage(imgixParams: { w: 320, h: 320 }) {
          width
          height
          src
          alt
        }
      }
      _status
      _firstPublishedAt
    }
  }
}
