query Post($id: ItemId!) {
  post(filter: { id: { eq: $id } }) {
    id
    slug
    title
    date
    content {
      __typename
      links
      blocks {
        __typename
        id
        ... on ProductRecord {
          shopifyProductId
        }
      }
      value
    }
    image {
      responsiveImage(imgixParams: { w: 640, h: 640 }) {
        width
        height
        src
        alt
      }
    }
    _status
    _firstPublishedAt
  }
}
