query Posts($skip: IntType) {
  allPosts(first: 100, skip: $skip) {
    id
    slug
    title
    date
    excerpt
    image {
      responsiveImage(
        imgixParams: { w: 120, h: 120, fit: crop, crop: focalpoint }
      ) {
        width
        height
        src
        alt
      }
    }
  }

  _allPostsMeta {
    count
  }
}
